<?php

namespace Database\Seeders;

use App\Models\Property;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Truncate first to avoid duplication
        \Illuminate\Support\Facades\DB::table('properties')->truncate();

        $properties = [
            [
                'title' => 'Apartemen Chilitown',
                'type' => 'apartemen',
                'price' => 6500000,
                'stars' => 5,
                'address' => 'Jl. Kembar No 45, Denpasar, Bali',
                'location' => 'Denpasar, Bali',
                'image' => 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=600',
                'description' => 'Apartemen mewah di pusat kota Denpasar. Dilengkapi dengan pemandangan kota malam hari yang memukau, interior berperabotan lengkap standar premium, serta akses langsung ke mal terdekat.',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area' => 60,
                'floors' => 12,
                'garage' => 'Basement Mandiri',
                'year_built' => 2022,
                'certificate' => 'SHMSRS',
                'electricity' => 2200,
                'water_source' => 'PDAM',
                'facilities' => ['Wifi', 'AC', 'TV Kabel', 'Lift', 'Security 24 Jam', 'Balkon'],
            ],
            [
                'title' => 'Villa Karangasem',
                'type' => 'villa',
                'price' => 14000000,
                'stars' => 4,
                'address' => 'Jl. Raya Besakih No. 10, Karangasem, Bali',
                'location' => 'Karangasem, Bali',
                'image' => 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=600',
                'description' => 'Vila asri dengan konsep alam terbuka di Karangasem. Suasana sunyi, sejuk, dan dekat dengan objek wisata bersejarah. Dilengkapi dengan kolam renang pribadi dan taman bunga yang indah.',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'area' => 180,
                'floors' => 2,
                'garage' => 'Carport 2 Mobil',
                'year_built' => 2020,
                'certificate' => 'SHM',
                'electricity' => 3500,
                'water_source' => 'Sumur Bor',
                'facilities' => ['Kolam Renang', 'Wifi', 'Dapur', 'Taman', 'Furniture', 'AC'],
            ],
            [
                'title' => 'Rumah Modern Ubud',
                'type' => 'rumah',
                'price' => 7500000,
                'stars' => 4,
                'address' => 'Jl. Kembar No 45, Mas, Ubud, Bali',
                'location' => 'Ubud, Bali',
                'image' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=600',
                'description' => 'Rumah bertema modern industrial dengan pemandangan lembah hijau Ubud yang menenangkan. Memiliki sirkulasi udara yang baik dan cahaya alami melimpah, sangat cocok untuk peristirahatan panjang.',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area' => 120,
                'floors' => 2,
                'garage' => 'Carport 1 Mobil',
                'year_built' => 2023,
                'certificate' => 'SHM',
                'electricity' => 2200,
                'water_source' => 'Sumur Bor',
                'facilities' => ['Pemandangan Sawah', 'Ruang kerja', 'Wifi', 'AC', 'Dapur', 'Taman'],
            ],
            [
                'title' => 'Apartemen Denpasar Heights',
                'type' => 'apartemen',
                'price' => 4800000,
                'stars' => 4,
                'address' => 'Jl. Raya Puputan No. 100, Renon, Denpasar, Bali',
                'location' => 'Denpasar, Bali',
                'image' => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=600',
                'description' => 'Apartemen studio dengan efisiensi ruang yang luar biasa. Sangat ideal untuk profesional muda maupun mahasiswa dengan mobilitas tinggi yang mencari keamanan serta kepraktisan tinggal.',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area' => 32,
                'floors' => 8,
                'garage' => 'Basement Bersama',
                'year_built' => 2019,
                'certificate' => 'HGB',
                'electricity' => 1300,
                'water_source' => 'PDAM',
                'facilities' => ['Wifi', 'AC', 'Laundry', 'Lift', 'CCTV', 'Furniture'],
            ],
            [
                'title' => 'Villa Arity Ubud Tepi',
                'type' => 'villa',
                'price' => 22000000,
                'stars' => 4,
                'address' => 'Jl. Nakula No 66, Ubud, Bali',
                'location' => 'Ubud, Bali',
                'image' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=600',
                'description' => 'Vila mewah di tepian tebing dengan suara gemercik sungai Ubud yang menenangkan. Unit ini didesain eksklusif dengan kolam renang infinity pool dan gazebo cantik untuk bersantai.',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'area' => 220,
                'floors' => 2,
                'garage' => 'Garasi Tertutup',
                'year_built' => 2021,
                'certificate' => 'SHM',
                'electricity' => 4400,
                'water_source' => 'Sumur Bor',
                'facilities' => ['Kolam Renang', 'Pemandangan Sawah', 'Wifi', 'Dapur', 'Balkon', 'Security 24 Jam'],
            ],
            [
                'title' => 'Rumah Minimalis Canggu',
                'type' => 'rumah',
                'price' => 8500000,
                'stars' => 4,
                'address' => 'Jl. Pantai Batu Bolong No. 12, Canggu, Badung, Bali',
                'location' => 'Canggu, Bali',
                'image' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=600',
                'description' => 'Hunian minimalis di perbatasan Canggu dengan arsitektur Skandinavia. Rumah ini menawarkan kenyamanan tinggal dalam desain tata ruang terbuka yang efisien dan dekorasi estetis.',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area' => 90,
                'floors' => 1,
                'garage' => 'Carport 1 Mobil',
                'year_built' => 2022,
                'certificate' => 'SHM',
                'electricity' => 2200,
                'water_source' => 'PDAM',
                'facilities' => ['Wifi', 'AC', 'Dapur', 'Taman', 'Furniture', 'Parkir Motor'],
            ],
            [
                'title' => 'Apartemen Ghilthon',
                'type' => 'apartemen',
                'price' => 5500000,
                'stars' => 4,
                'address' => 'Jl. Kembar No 45, Denpasar, Bali',
                'location' => 'Denpasar, Bali',
                'image' => 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=600',
                'description' => 'Unit apartemen premium di lantai atas dengan tata kelola profesional. Menyajikan nuansa hotel berbintang dengan perabotan eksklusif dan pemandangan cakrawala kota yang megah.',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area' => 75,
                'floors' => 18,
                'garage' => 'Basement Khusus',
                'year_built' => 2021,
                'certificate' => 'SHMSRS',
                'electricity' => 3500,
                'water_source' => 'PDAM',
                'facilities' => ['HDTV 45 inci dengan Netflix', 'AC', 'Wifi', 'Lift', 'Gym', 'Security 24 Jam'],
            ],
            [
                'title' => 'Villa Canggu',
                'type' => 'villa',
                'price' => 28000000,
                'stars' => 5,
                'address' => 'Jl. Pantai Batu Belig No. 8, Canggu, Badung, Bali',
                'location' => 'Canggu, Bali',
                'image' => 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=600',
                'description' => 'Vila tropis modern yang berlokasi di area strategis Canggu. Hanya berjarak 5 menit dari pantai, vila ini memiliki kolam renang terbuka, area berjemur, serta dapur bar yang trendi.',
                'bedrooms' => 4,
                'bathrooms' => 4,
                'area' => 300,
                'floors' => 2,
                'garage' => 'Garasi 2 Mobil',
                'year_built' => 2020,
                'certificate' => 'SHM',
                'electricity' => 5500,
                'water_source' => 'Sumur Bor',
                'facilities' => ['Kolam Renang', 'Wifi', 'Dapur', 'AC', 'Taman', 'CCTV'],
            ],
            [
                'title' => 'Rumah Minimalis Ubud',
                'type' => 'rumah',
                'price' => 6000000,
                'stars' => 5,
                'address' => 'Jl. Kamboja No 40, Ubud, Bali',
                'location' => 'Ubud, Bali',
                'image' => 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&q=80&w=600',
                'description' => 'Rumah bernuansa tradisional-modern yang dikelilingi pepohonan asri di pinggiran Ubud. Pilihan ideal untuk mencari ketenangan berkarya, menulis, maupun memulihkan diri.',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area' => 110,
                'floors' => 1,
                'garage' => 'Carport 1 Mobil',
                'year_built' => 2018,
                'certificate' => 'SHM',
                'electricity' => 2200,
                'water_source' => 'Sumur Bor',
                'facilities' => ['Ruang kerja', 'Wifi', 'Dapur', 'Taman', 'Furniture', 'Parkir Motor'],
            ],
            [
                'title' => 'Apartemen Signature Jimbaran',
                'type' => 'apartemen',
                'price' => 25000000,
                'stars' => 5,
                'address' => 'Kawasan ITDC Lot N5, Jimbaran, Bali',
                'location' => 'Jimbaran, Bali',
                'image' => 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=600',
                'description' => 'Apartemen super mewah di kawasan premium Jimbaran Bali. Dilengkapi fasilitas berkelas dunia, lift privat menuju unit, pemandangan laut selatan Bali, dan tingkat keamanan setingkat resor bintang lima.',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'area' => 150,
                'floors' => 35,
                'garage' => 'Privat Basement',
                'year_built' => 2024,
                'certificate' => 'SHMSRS',
                'electricity' => 6600,
                'water_source' => 'PDAM',
                'facilities' => ['HDTV 45 inci dengan Netflix', 'AC', 'Wifi', 'Gym', 'Lift', 'Security 24 Jam'],
            ],
            [
                'title' => 'Villa Uluwatu Cliffside',
                'type' => 'villa',
                'price' => 45000000,
                'stars' => 5,
                'address' => 'Pecatu, Kuta Selatan, Badung, Bali',
                'location' => 'Uluwatu, Bali',
                'image' => 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&q=80&w=600',
                'description' => 'Vila tebing laut termewah dengan pemandangan Samudra Hindia 180 derajat yang memukau. Menghadirkan infinity pool luas, akses privat, arsitektur megah kelas dunia, dan layanan butler eksklusif.',
                'bedrooms' => 5,
                'bathrooms' => 5,
                'area' => 600,
                'floors' => 2,
                'garage' => 'Garasi 4 Mobil',
                'year_built' => 2023,
                'certificate' => 'SHM',
                'electricity' => 11000,
                'water_source' => 'Sumur Bor',
                'facilities' => ['Kolam Renang', 'Wifi', 'Dapur', 'Balkon', 'Security 24 Jam', 'CCTV'],
            ],
            [
                'title' => 'Rumah Modern Sanur',
                'type' => 'rumah',
                'price' => 9500000,
                'stars' => 4,
                'address' => 'Jl. Danau Tamblingan No. 24, Sanur, Bali',
                'location' => 'Denpasar, Bali',
                'image' => 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&q=80&w=600',
                'description' => 'Rumah tinggal keluarga modern di kawasan tenang Sanur. Keamanan 24 jam dengan sistem satu pintu masuk (one-gate system), lingkungan sangat ramah anak, dan dekat dengan pantai matahari terbit.',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 140,
                'floors' => 2,
                'garage' => 'Carport 2 Mobil',
                'year_built' => 2021,
                'certificate' => 'SHM',
                'electricity' => 3500,
                'water_source' => 'PDAM',
                'facilities' => ['Wifi', 'AC', 'Dapur', 'Taman', 'Playground', 'Security 24 Jam'],
            ],
            [
                'title' => 'Apartemen Cozy Kuta',
                'type' => 'apartemen',
                'price' => 4000000,
                'stars' => 3,
                'address' => 'Jl. Raya Kuta No. 88, Kuta, Bali',
                'location' => 'Badung, Bali',
                'image' => 'https://images.unsplash.com/photo-1515263487990-61b07816b324?auto=format&fit=crop&q=80&w=600',
                'description' => 'Unit apartemen tipe studio yang nyaman dan terjangkau di pusat wisata Kuta. Dekat dengan pantai, tempat kuliner, dan akses bandara, sangat cocok untuk tempat hunian wisatawan panjang.',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area' => 28,
                'floors' => 5,
                'garage' => 'Parkiran Bersama',
                'year_built' => 2017,
                'certificate' => 'HGB',
                'electricity' => 1300,
                'water_source' => 'PDAM',
                'facilities' => ['Wifi', 'AC', 'Lift', 'Furniture', 'Parkir Motor', 'CCTV'],
            ],
            [
                'title' => 'Villa Seminyak Garden',
                'type' => 'villa',
                'price' => 18000000,
                'stars' => 4,
                'address' => 'Jl. Drupadi No 10X, Seminyak, Bali',
                'location' => 'Seminyak, Bali',
                'image' => 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=600',
                'description' => 'Vila bergaya semi-terbuka dengan taman tropis rimbun di pusat Seminyak. Memberikan ketenangan di tengah pusat keramaian belanja, butik fashion, dan jajaran restoran terkenal.',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'area' => 250,
                'floors' => 1,
                'garage' => 'Carport 1 Mobil',
                'year_built' => 2019,
                'certificate' => 'SHM',
                'electricity' => 4400,
                'water_source' => 'Sumur Bor',
                'facilities' => ['Kolam Renang', 'Wifi', 'Dapur', 'Taman', 'Furniture', 'AC'],
            ],
            [
                'title' => 'Rumah Kayu Kintamani',
                'type' => 'rumah',
                'price' => 5000000,
                'stars' => 4,
                'address' => 'Jl. Raya Penelokan, Kintamani, Bali',
                'location' => 'Bangli, Bali',
                'image' => 'https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&q=80&w=600',
                'description' => 'Rumah kayu berkonsep villa etnik Jawa di kawasan berudara sangat sejuk Kintamani, Bali. Dikelilingi pemandangan Gunung Batur yang megah, sangat syahdu untuk menenangkan pikiran.',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area' => 150,
                'floors' => 1,
                'garage' => 'Halaman Luas',
                'year_built' => 2016,
                'certificate' => 'SHM',
                'electricity' => 1300,
                'water_source' => 'Sumur Bor',
                'facilities' => ['Taman', 'Wifi', 'Dapur', 'Furniture', 'Ruang kerja', 'Parkir Motor'],
            ]
        ];

        foreach ($properties as $property) {
            $property['views'] = rand(50, 450);
            Property::create($property);
        }
    }
}
